version: "3.8"

services:
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    ports:
      - "80:80"
